from fastapi import FastAPI, UploadFile, File, Form
from fastapi.responses import JSONResponse, RedirectResponse
from fastapi.staticfiles import StaticFiles
import uvicorn
import tempfile
import os
import json
from typing import Optional, List
from html import escape

from prototype_waterbody_detection import run_detection

app = FastAPI(title="Waterbody Buffer Detection API")


def _write_report_pdf(report, output_path, run_id):
    """Write a readable PDF summary for a completed detection run."""
    from reportlab.lib import colors
    from reportlab.lib.pagesizes import A4
    from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
    from reportlab.lib.units import mm
    from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle

    styles = getSampleStyleSheet()
    styles.add(ParagraphStyle(name="SmallMuted", parent=styles["Normal"], fontSize=8.5, textColor=colors.HexColor("#64748b"), leading=12))
    styles.add(ParagraphStyle(name="Section", parent=styles["Heading2"], fontSize=13, textColor=colors.HexColor("#164e63"), spaceBefore=12, spaceAfter=7))
    styles["Title"].textColor = colors.HexColor("#0f3d3e")
    styles["Title"].fontSize = 23

    def safe(value):
        return escape(str(value if value is not None else ""))

    summary = report.get("summary", {})
    quality = report.get("data_quality", {})
    violations = report.get("violations", [])
    findings = report.get("findings", [])
    issues = report.get("issues", [])
    doc = SimpleDocTemplate(output_path, pagesize=A4, rightMargin=16 * mm, leftMargin=16 * mm, topMargin=15 * mm, bottomMargin=15 * mm)
    story = [Paragraph("Waterbody Buffer Detection", styles["Title"]), Paragraph(f"Analysis report | Run {safe(run_id)}", styles["SmallMuted"]), Spacer(1, 10)]
    story.append(Paragraph("Executive summary", styles["Section"]))
    summary_rows = [["Status", safe(summary.get("status", "unknown"))], ["Confidence", safe(summary.get("confidence", "unknown"))], ["Violations found", safe(summary.get("violations_found", len(violations)))], ["Water source", safe(quality.get("water_source", "unknown"))], ["Water features", safe(quality.get("water_feature_count", "unknown"))]]
    table = Table(summary_rows, colWidths=[48 * mm, 120 * mm])
    table.setStyle(TableStyle([("BACKGROUND", (0, 0), (0, -1), colors.HexColor("#e8f4ee")), ("GRID", (0, 0), (-1, -1), .35, colors.HexColor("#cbded3")), ("FONTNAME", (0, 0), (0, -1), "Helvetica-Bold"), ("VALIGN", (0, 0), (-1, -1), "TOP"), ("PADDING", (0, 0), (-1, -1), 7)]))
    story.append(table)
    story.append(Paragraph("Buffer checks", styles["Section"]))
    rows = [["Buffer", "Intersects", "Intersections"]]
    rows.extend([[f"{item.get('buffer_m', '')} m", "Yes" if item.get("intersects") else "No", str(item.get("num_intersections", 0))] for item in violations])
    if len(rows) == 1:
        rows.append(["-", "No violations recorded", "-"])
    checks = Table(rows, colWidths=[45 * mm, 55 * mm, 55 * mm], repeatRows=1)
    checks.setStyle(TableStyle([("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#164e63")), ("TEXTCOLOR", (0, 0), (-1, 0), colors.white), ("GRID", (0, 0), (-1, -1), .35, colors.HexColor("#cbd5e1")), ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, colors.HexColor("#f5faf7")]), ("PADDING", (0, 0), (-1, -1), 7)]))
    story.append(checks)
    if findings or issues:
        story.append(Paragraph("Findings and notes", styles["Section"]))
        for item in findings:
            story.append(Paragraph(f"<b>{safe(item.get('risk', 'note')).upper()}</b> - {safe(item.get('message', ''))}", styles["Normal"]))
        for issue in issues:
            story.append(Paragraph(f"- {safe(issue)}", styles["Normal"]))
    story.append(Spacer(1, 12))
    story.append(Paragraph("Generated by the Waterbody Buffer Detection dashboard. Use the evidence GeoJSON and map artifact for spatial verification.", styles["SmallMuted"]))
    doc.build(story)


@app.get("/")
async def root():
    return RedirectResponse(url="/demo/")


@app.get("/health")
async def health():
    return {"status": "ok", "outputs_dir": "outputs"}


@app.get("/runs")
async def list_runs():
    runs = []
    if os.path.isdir("outputs"):
        for entry in sorted(os.listdir("outputs"), reverse=True):
            path = os.path.join("outputs", entry)
            if not os.path.isdir(path):
                continue
            report_path = os.path.join(path, "report.json")
            report_pdf_path = os.path.join(path, "report.pdf")
            evidence_path = os.path.join(path, "evidence.geojson")
            map_path = os.path.join(path, "map.png")
            runs.append({
                "id": entry,
                "report_url": f"/outputs/{entry}/report.json" if os.path.exists(report_path) else None,
                "report_pdf_url": f"/outputs/{entry}/report.pdf" if os.path.exists(report_pdf_path) else None,
                "evidence_url": f"/outputs/{entry}/evidence.geojson" if os.path.exists(evidence_path) else None,
                "map_url": f"/outputs/{entry}/map.png" if os.path.exists(map_path) else None,
            })
    return {"runs": runs[:10]}


def _bbox_from_geojson_payload(payload):
    """Return bbox from a GeoJSON object as (minlon, minlat, maxlon, maxlat)."""
    xs = []
    ys = []

    def walk(obj):
        if isinstance(obj, dict):
            if "coordinates" in obj:
                walk(obj["coordinates"])
            if "geometry" in obj and obj["geometry"] is not None:
                walk(obj["geometry"])
            if "features" in obj:
                for item in obj["features"]:
                    walk(item)
            if "feature" in obj:
                walk(obj["feature"])
        elif isinstance(obj, list):
            if obj and all(isinstance(v, (int, float)) for v in obj[:2]):
                if len(obj) >= 2:
                    xs.append(float(obj[0]))
                    ys.append(float(obj[1]))
            else:
                for item in obj:
                    walk(item)

    walk(payload)
    if not xs or not ys:
        return None

    buffer_pad = max(0.01, (max(xs) - min(xs)) * 0.15, (max(ys) - min(ys)) * 0.15)
    return (min(xs) - buffer_pad, min(ys) - buffer_pad, max(xs) + buffer_pad, max(ys) + buffer_pad)


def _bbox_from_point(lon: float, lat: float, pad_deg: float = 0.01):
    return (lon - pad_deg, lat - pad_deg, lon + pad_deg, lat + pad_deg)


# Serve outputs directory (created on demand)
os.makedirs("outputs", exist_ok=True)
app.mount("/outputs", StaticFiles(directory="outputs"), name="outputs")

# Serve built frontend if available, otherwise fall back to the simple static demo.
if os.path.isdir("dist"):
    app.mount("/demo", StaticFiles(directory="dist", html=True), name="demo")
elif os.path.isdir("frontend"):
    app.mount("/demo", StaticFiles(directory="frontend", html=True), name="demo")


@app.post("/detect")
async def detect(
    bbox: Optional[str] = Form(None),
    project_point: Optional[str] = Form(None),
    buffers: Optional[str] = Form(None),
    enable_ndwi: Optional[bool] = Form(False),
    ndwi_start: Optional[str] = Form(None),
    ndwi_end: Optional[str] = Form(None),
    ec_pdf: Optional[UploadFile] = File(None),
    project_geojson: Optional[UploadFile] = File(None),
):
    """Run detection. Either upload project_geojson or provide project_point.

    If bbox is omitted, it is inferred from the project geometry or project_point.
    Returns JSON with report and links to outputs.
    """
    proj_point_tuple = None
    if project_point:
        try:
            lon, lat = [float(x) for x in project_point.split(",")]
            proj_point_tuple = (lon, lat)
        except Exception:
            return JSONResponse(status_code=400, content={"error": "project_point must be lon,lat"})

    project_geojson_path = None
    if project_geojson:
        contents = await project_geojson.read()
        project_geojson_path = os.path.join("outputs", next(tempfile._get_candidate_names()), project_geojson.filename or "project.geojson")
        os.makedirs(os.path.dirname(project_geojson_path), exist_ok=True)
        with open(project_geojson_path, "wb") as f:
            f.write(contents)

    if bbox:
        try:
            bbox_vals = tuple(float(x) for x in bbox.split(","))
        except Exception:
            return JSONResponse(status_code=400, content={"error": "bbox must be minlon,minlat,maxlon,maxlat"})
    else:
        if project_geojson_path:
            try:
                with open(project_geojson_path, "r", encoding="utf-8") as f:
                    payload = json.load(f)
                derived = _bbox_from_geojson_payload(payload)
                if derived is None:
                    raise ValueError("No coordinates found in GeoJSON")
                bbox_vals = derived
            except Exception:
                if proj_point_tuple is None:
                    return JSONResponse(status_code=400, content={"error": "bbox is required when project file has no coordinates or when no project point is given"})
                bbox_vals = _bbox_from_point(*proj_point_tuple)
        elif proj_point_tuple is not None:
            bbox_vals = _bbox_from_point(*proj_point_tuple)
        else:
            return JSONResponse(status_code=400, content={"error": "bbox is required unless project_point or project_geojson is provided"})

    buffer_list = [30.0, 50.0, 100.0]
    if buffers:
        try:
            buffer_list = [float(x) for x in buffers.split(",")]
        except Exception:
            return JSONResponse(status_code=400, content={"error": "buffers must be comma-separated numbers"})

    if isinstance(enable_ndwi, str):
        enable_ndwi_flag = enable_ndwi.lower() in ("1", "true", "yes", "on")
    else:
        enable_ndwi_flag = bool(enable_ndwi)

    out_dir = os.path.join("outputs", next(tempfile._get_candidate_names()))
    os.makedirs(out_dir, exist_ok=True)

    if project_geojson and project_geojson_path and os.path.exists(project_geojson_path):
        # move uploaded project geojson into the run output directory for traceability
        target_path = os.path.join(out_dir, project_geojson.filename or "project.geojson")
        if project_geojson_path != target_path:
            with open(project_geojson_path, "rb") as src, open(target_path, "wb") as dst:
                dst.write(src.read())
            project_geojson_path = target_path

    # If an EC PDF is provided, try to parse buffer distances from it
    parsed_buffers = None
    ec_parse_path = None
    if ec_pdf:
        from ec_parser import parse_ec_pdf
        contents = await ec_pdf.read()
        pdf_path = os.path.join(out_dir, ec_pdf.filename or "ec.pdf")
        with open(pdf_path, "wb") as f:
            f.write(contents)
        try:
            parsed = parse_ec_pdf(pdf_path)
            parsed_buffers = parsed.get('buffers_m', [])
        except Exception as e:
            parsed = {'buffers_m': [], 'llm_used': False, 'llm_error': str(e), 'raw_text': ''}
            parsed_buffers = []
        try:
            ec_parse_path = os.path.join(out_dir, 'ec_parse.json')
            with open(ec_parse_path, 'w', encoding='utf-8') as pf:
                json.dump(parsed, pf, indent=2)
        except Exception:
            ec_parse_path = None

    if parsed_buffers and len(parsed_buffers) > 0 and not buffers:
        buffer_list = parsed_buffers

    try:
        result = run_detection(
            bbox_vals,
            project_geojson_path=project_geojson_path,
            project_point=proj_point_tuple,
            buffers=buffer_list,
            out_dir=out_dir,
            enable_ndwi=enable_ndwi_flag,
            ndwi_dates=(ndwi_start, ndwi_end),
        )
    except Exception as e:
        return JSONResponse(status_code=500, content={"error": str(e)})

    report_pdf_path = os.path.join(out_dir, "report.pdf")
    try:
        _write_report_pdf(result["report"], report_pdf_path, os.path.basename(out_dir))
    except Exception:
        report_pdf_path = None

    ec_parse_url = None
    if ec_parse_path:
        ec_parse_url = f"/outputs/{os.path.basename(out_dir)}/ec_parse.json"

    base_url = f"/outputs/{os.path.basename(out_dir)}"
    response = {
        "run_id": os.path.basename(out_dir),
        "report": result["report"],
        "report_url": base_url + "/report.json",
        "report_pdf_url": base_url + "/report.pdf" if report_pdf_path else None,
        "evidence_url": base_url + "/evidence.geojson",
        "map_url": base_url + "/map.png",
    }
    if result.get("ndwi_path"):
        response["ndwi_url"] = base_url + "/ndwi.png"
    if result.get("ndwi_error"):
        response["ndwi_error"] = result.get("ndwi_error")
    if ec_parse_url:
        response["ec_parse_url"] = ec_parse_url

    return JSONResponse(status_code=200, content=response)


if __name__ == "__main__":
    uvicorn.run("app:app", host="127.0.0.1", port=8000)
